spring.datasource.url=jdbc:postgresql://localhost:5432/chatdb
spring.datasource.username=postgres
spring.datasource.password=Sanjay@9078

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG